set(STM32_TARGET_NAME stm32f4 CACHE INTERNAL "")
set(STM32_MCU_FAMILY STM32F4xx CACHE INTERNAL "")
set(STM32_DEVICE_DEFINE STM32F407xx CACHE INTERNAL "")
set(STM32_DENSITY_DEFINE STM32F40_41xxx CACHE INTERNAL "")
set(STM32_HSE_VALUE 8000000 CACHE INTERNAL "")
set(STM32_FREERTOS_PORT GCC_ARM_CM4F CACHE INTERNAL "")

set(STM32_CPU_PARAMETERS
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=hard
    CACHE INTERNAL "")

set(STM32_STARTUP_SCRIPT ${CMAKE_CURRENT_LIST_DIR}/STM32F407xx.s CACHE INTERNAL "")
set(STM32_LINKER_SCRIPT ${CMAKE_CURRENT_LIST_DIR}/STM32F407xG.ld CACHE INTERNAL "")

set(STM32_PLATFORM_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/board.cpp
    ${CMAKE_CURRENT_LIST_DIR}/drivers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/interrupts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/system_stm32f4xx.c
    CACHE INTERNAL "")

set(STM32_STD_LIB_ROOT ${CMAKE_SOURCE_DIR}/STM32F4_Driver CACHE INTERNAL "")
set(STM32_STD_LIB_INCLUDE_DIRECTORIES
    ${STM32_STD_LIB_ROOT}/${STM32_MCU_FAMILY}_StdPeriph_Driver/inc
    ${STM32_STD_LIB_ROOT}/CMSIS/Device/ST/${STM32_MCU_FAMILY}/Include
    ${STM32_STD_LIB_ROOT}/CMSIS/Include
    CACHE INTERNAL "")

file(GLOB_RECURSE STM32_STD_LIB_SOURCES
    ${STM32_STD_LIB_ROOT}/${STM32_MCU_FAMILY}_StdPeriph_Driver/src/*.c)
