set(STM32_TARGET_NAME stm32f1 CACHE INTERNAL "")
set(STM32_MCU_FAMILY STM32F10x CACHE INTERNAL "")
set(STM32_DEVICE_DEFINE STM32F103xx CACHE INTERNAL "")
set(STM32_DENSITY_DEFINE STM32F10X_LD CACHE INTERNAL "")
set(STM32_HSE_VALUE 8000000 CACHE INTERNAL "")
set(STM32_FREERTOS_PORT GCC_ARM_CM3 CACHE INTERNAL "")

set(STM32_CPU_PARAMETERS
    -mcpu=cortex-m3
    -mthumb
    -mno-thumb-interwork
    -mfpu=vfp
    -msoft-float
    -mfix-cortex-m3-ldrd
    CACHE INTERNAL "")

set(STM32_STARTUP_SCRIPT ${CMAKE_CURRENT_LIST_DIR}/STM32F103x6.s CACHE INTERNAL "")
set(STM32_LINKER_SCRIPT ${CMAKE_CURRENT_LIST_DIR}/STM32F103x6.ld CACHE INTERNAL "")

set(STM32_PLATFORM_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/board.cpp
    ${CMAKE_CURRENT_LIST_DIR}/drivers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/interrupts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/system_stm32f10x.c
    CACHE INTERNAL "")

set(STM32_STD_LIB_ROOT ${CMAKE_SOURCE_DIR}/stm32f10x-stdperiph-lib CACHE INTERNAL "")
set(STM32_STD_LIB_INCLUDE_DIRECTORIES
    ${STM32_STD_LIB_ROOT}/Libraries/${STM32_MCU_FAMILY}_StdPeriph_Driver/inc
    ${STM32_STD_LIB_ROOT}/Libraries/CMSIS/CM3/DeviceSupport/ST/${STM32_MCU_FAMILY}
    ${STM32_STD_LIB_ROOT}/Libraries/CMSIS/CM3/CoreSupport
    CACHE INTERNAL "")

file(GLOB_RECURSE STM32_STD_LIB_SOURCES
    ${STM32_STD_LIB_ROOT}/Libraries/${STM32_MCU_FAMILY}_StdPeriph_Driver/src/*.c)
